spring:
  config:
    import: application-secrets.yml
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none


cookie:
  secure: false
  domain: "localhost"

accessToken:
  time: 7200000 # 1000 * 10
---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://database-1.cue4jecs154j.ap-northeast-2.rds.amazonaws.com:3306/socceranalystdb?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: sksjsksh32
    password: 963741dsa!

cookie:
  secure: true
  domain: "socceranalyst.net"

accessToken:
  time: 7200000 # 1000 * 60 * 60 * 2
---
# 공통 구성
logging:
  level:
    root: INFO
    soccer.backend: INFO
    org:
      springframework:
        security: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: loggers
      base-path: "/dev/actuator"

spring:
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      password:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher




