jwt:
  secret-key: "fasdfasasdflknewqiofdsalkfnqwouie234231412fkdsjafbeuwqpfbdsadflfbasfklwuiqefblskf34214asdkljfbsaldrasdrkljfb"

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none

cookie:
  secure: false
  domain: "localhost"

accessToken:
  time: 7200000 # 1000 * 10
---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url:
    username:
    password:

cookie:
  secure: true
  domain: "socceranalyst.net"

accessToken:
  time: 7200000 # 1000 * 60 * 60 * 2
---
# 공통 구성
logging:
  level:
    root: INFO
    soccer.backend: INFO
    org:
      springframework:
        security: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: loggers
      base-path: "/dev/actuator"

spring:
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      password:



